// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxC5DcrsPsMOX0qzX-LZgeYntQl-1UOpM',
    appId: '1:930273473052:web:34174b9fafd7f3cb2065d9',
    messagingSenderId: '930273473052',
    projectId: 'hamrochat-9a201',
    authDomain: 'hamrochat-9a201.firebaseapp.com',
    databaseURL: 'https://hamrochat-9a201-default-rtdb.firebaseio.com',
    storageBucket: 'hamrochat-9a201.appspot.com',
    measurementId: 'G-02F6MNND92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3n_vBH203EX7I3ot0Ic3q67aW9Lzq0AE',
    appId: '1:930273473052:android:ef5f2df6ba79e6c12065d9',
    messagingSenderId: '930273473052',
    projectId: 'hamrochat-9a201',
    databaseURL: 'https://hamrochat-9a201-default-rtdb.firebaseio.com',
    storageBucket: 'hamrochat-9a201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdmVdN-8-Wg6wmV3XM2WVr5OufKwG3rW0',
    appId: '1:930273473052:ios:5198576030bf949e2065d9',
    messagingSenderId: '930273473052',
    projectId: 'hamrochat-9a201',
    databaseURL: 'https://hamrochat-9a201-default-rtdb.firebaseio.com',
    storageBucket: 'hamrochat-9a201.appspot.com',
    androidClientId: '930273473052-26bic2382g8ftj39qbfdsi66dpof0h73.apps.googleusercontent.com',
    iosClientId: '930273473052-stvast45b1bse177ajebqei7cbtjqouq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hamrochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdmVdN-8-Wg6wmV3XM2WVr5OufKwG3rW0',
    appId: '1:930273473052:ios:5198576030bf949e2065d9',
    messagingSenderId: '930273473052',
    projectId: 'hamrochat-9a201',
    databaseURL: 'https://hamrochat-9a201-default-rtdb.firebaseio.com',
    storageBucket: 'hamrochat-9a201.appspot.com',
    androidClientId: '930273473052-26bic2382g8ftj39qbfdsi66dpof0h73.apps.googleusercontent.com',
    iosClientId: '930273473052-stvast45b1bse177ajebqei7cbtjqouq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hamrochat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxC5DcrsPsMOX0qzX-LZgeYntQl-1UOpM',
    appId: '1:930273473052:web:39bac188d90267b82065d9',
    messagingSenderId: '930273473052',
    projectId: 'hamrochat-9a201',
    authDomain: 'hamrochat-9a201.firebaseapp.com',
    databaseURL: 'https://hamrochat-9a201-default-rtdb.firebaseio.com',
    storageBucket: 'hamrochat-9a201.appspot.com',
    measurementId: 'G-WFVWSTK8TJ',
  );
}
